### ISSUE TITLE
[TypeScript] can't reference D2RMM's own types in mods because the definitions are outside of the /mods/ folder

### ISSUE THREAD

**Issue by Caedendi** [olegbl/d2rmm#30]
TypeScript support has been a blessing for my modding. One issue that I've run into a few times though is that D2RMM doesn't support its own types.

To reproduce, add this file to a mod and try to install it.

_(Don't mind the technical side of what the code is supposed to do, it's still a work in progress)_

``` TypeScript
import { JSONData } from "../../types"; // PROBLEM HERE

export class GameDataTest {
  protected skillsJsonFile: JSONData;

  constructor() {
    this.loadFiles();
    let row = this.findJsonFileEntryByKey(this.skillsJsonFile, "skillname59"); // blizzard
  }

  protected loadFiles(): void {
    this.skillsJsonFile = D2RMM.readJson(`global\\excel\\skills.json`);
  }


  protected findJsonFileEntryByKey(jsonFile: JSONData, key: string): Record<string, string> { // PROBLEM HERE
    let match = Object.entries(jsonFile).find(([_, value]) => value["key"] === key);
    return match ? { [match[0]]: match[1]["key"] } : {};
  }
}
```

D2RMM will give this error message:

```
[MOD NAME] Mod encountered a compile error!
Error: BridgeAPI.readModCode: Failed to compile mod: Error: BridgeAPI.readModCode: Failed to read mods\MODFOLDER\../../types.ts
    at I (C:\Users\Caedendi\Games\D2RMM\resources\app.asar\dist\main\worker.js:2:163626)
    at Object.readModCode (C:\Users\Caedendi\Games\D2RMM\resources\app.asar\dist\main\worker.js:2:174289)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async installMods (C:\Users\Caedendi\Games\D2RMM\resources\app.asar\dist\main\worker.js:2:176643)
```

**Comment by olegbl** [comment]
So, the way `types.d.ts` works is a bit magical in that any TS environment should automatically import the nearest `types.d.ts` up the directory structure without you having to specify it. So, you shouldn't ever need to import it manually like this.

**Comment by Caedendi** [comment]
Well I guess that seems to work, but it still leaves me with my IDE showing a lot of errors because it can't find those types. Is there a way to fix that?

**Comment by olegbl** [comment]
Oh, I think I understand your question - you want to reference the types in `types.d.ts` (such as `JSONData`) directly rather than just having types for D2RMM APIs. I think I'd just need to declare those types globally in types.d.ts.

**Comment by Caedendi** [comment]
Exactly, that's what I meant. For this line right here:

``` TypeScript
protected findJsonFileEntryByKey(jsonFile: JSONData, key: string): Record<string, string> { // PROBLEM HERE
```

So I can demand `jsonFile` to be of type `JSONData`.

**Comment by olegbl** [comment]
BTW, until the exporting is done, you can always derive these types. e.g.:
```
type MethodReturn<TMethod> = TMethod extends (
  ...args: infer TArgs
) => infer TReturn
  ? TReturn
  : never;

type JSONData = MethodReturn<typeof D2RMM.readJson>;
```

**Comment by bviktor** [comment]
Well symlinks don't really work in Git for Windows, like at all. And I wasn't really keen on going to Linux just for this. I'm not too keen about adding symlinks to the repo either I guess.

The workaround I talked about earlier turned out to be not so great, too. It only worked if I opened single files, but not when I opened my repo as a folder. When opened as a folder, VS Code would follow the symlink no matter what, and we're back to square one, unknown symbols.

So I ended up with a `tsconfig.json` like so:

```json
{
	"compilerOptions":{
		"types": ["../d2rmm/src/mods/types.d.ts"]
	}
}
```

This seems to work fine both with single files and with folders. The only thing that needs to be adhered to is directory structure, i.e. my repo needs to be adjacent to your repo, and that's it.
